name: ci

on:
  push:
    tags:
      - "*"
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"

jobs:

  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      working_directory: .
      cache_from: |
        docker.io/klutchell/dnscrypt-proxy:main
        ghcr.io/klutchell/dnscrypt-proxy:main
        docker.io/klutchell/dnscrypt-proxy:latest
        ghcr.io/klutchell/dnscrypt-proxy:latest
      images: |
        docker.io/klutchell/dnscrypt-proxy
        ghcr.io/klutchell/dnscrypt-proxy
      platforms: |
        linux/amd64
        linux/arm64
        linux/arm/v7
        linux/arm/v6
      publish: true
      dockerhub_description_repo: klutchell/dnscrypt-proxy
